#! /bin/sh

# Start polybar
$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom -b &


if [[ $(xrandr -q | grep "HDMI-1 connected") ]]; then
  xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1 --mode 1920x1080 --rate 75.00 --rotate normal --left-of eDP-1
  bspc monitor eDP-1 -d 1 2 3 4 
  bspc monitor HDMI-1 -d 5 6 7 8
  nitrogen --head=1 --set-scaled ~/Wallpapers/wallhaven-5g5p23_1920x1080.png &
else
  bspc monitor -d 1 2 3 4 5 6
fi

nitrogen --head=0 --set-scaled ~/Wallpapers/wallhaven-5g5p23_1920x1080.png &

bspc config border_width            2
bspc config window_gap              16

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
# bspc config single_monocle          true
bspc config focus_follows_pointer   true

# Application specific rules
bspc rule -a chromium desktop="^2"
bspc rule -a Thunar desktop="^5"
bspc rule -a obsidian desktop="^6"
bspc rule -a Pavucontrol state=floating rectangle=473x288+1431+54 focus=off follow=off sticky=on
bspc rule -a Gsimplecal state=floating rectangle=250x188+1654+52 focus=off follow=off sticky=on

# Android studio visual fix
wmname LG3D &
bspc rule -a android-studio state=floating border=off follow=on

# Theme
# bspc config normal_border_color         xrdb -query | grep "*color0" | cut -f 2
# bspc config active_border_color         xrdb -query | grep "*color4" | cut -f 2
# bspc config focused_border_color        xrdb -query | grep "*color4" | cut -f 2
# bspc config presel_feedback_color       xrdb -query | grep "*color5" | cut -f 2
# bspc config urgent_border_color         xrdb -query | grep "*color1" | cut -f 2
bspc config normal_border_color         xrdb -query | grep "*color0" | cut -f 2
bspc config active_border_color         xrdb -query | grep "*color4" | cut -f 2
bspc config focused_border_color        xrdb -query | grep "*color4" | cut -f 2
bspc config presel_feedback_color       xrdb -query | grep "*color5" | cut -f 2
bspc config urgent_border_color         xrdb -query | grep "*color1" | cut -f 2

