#! /bin/sh

# Start polybar
$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom -b &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width            2
bspc config window_gap              16

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
# bspc config single_monocle          true

# Application specific rules
bspc rule -a chromium desktop="^1"
bspc rule -a Pavucontrol state=floating rectangle=473x288+1431+54 focus=off follow=off sticky=on
bspc rule -a Gsimplecal state=floating rectangle=250x188+1654+52 focus=off follow=off sticky=on

# Android studio visual fix
wmname LG3D &
bspc rule -a android-studio state=floating border=off follow=on

# Theme
bspc config normal_border_color         xrdb -query | grep "*color0" | cut -f 2
bspc config active_border_color         xrdb -query | grep "*color4" | cut -f 2
bspc config focused_border_color        xrdb -query | grep "*color4" | cut -f 2
bspc config presel_feedback_color       xrdb -query | grep "*color5" | cut -f 2
bspc config urgent_border_color         xrdb -query | grep "*color1" | cut -f 2

